version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /Users/santhoshraju/Documents/docker-practice/app:/project/app
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
